"""market/symbol_master.py — Static master list of supported demo symbols."""

from app.portfolios.schemas import ExchangeFilter

# A curated list of US large-cap and Indian equities for demo and autocomplete purposes.
# In a full production system, this would be backed by a daily-updated database table.

SYMBOL_MASTER: list[dict[str, str]] = [
    # ── US — NYSE / NASDAQ ──────────────────────────────────────────────────
    {"symbol": "AAPL", "name": "Apple Inc.", "exchange": "NASDAQ"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "exchange": "NASDAQ"},
    {"symbol": "GOOGL", "name": "Alphabet Inc. (Class A)", "exchange": "NASDAQ"},
    {"symbol": "AMZN", "name": "Amazon.com Inc.", "exchange": "NASDAQ"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "exchange": "NASDAQ"},
    {"symbol": "META", "name": "Meta Platforms Inc.", "exchange": "NASDAQ"},
    {"symbol": "TSLA", "name": "Tesla Inc.", "exchange": "NASDAQ"},
    {"symbol": "BRK-B", "name": "Berkshire Hathaway B", "exchange": "NYSE"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "exchange": "NYSE"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "exchange": "NYSE"},
    {"symbol": "V", "name": "Visa Inc.", "exchange": "NYSE"},
    {"symbol": "UNH", "name": "UnitedHealth Group", "exchange": "NYSE"},
    {"symbol": "XOM", "name": "ExxonMobil Corporation", "exchange": "NYSE"},
    {"symbol": "WMT", "name": "Walmart Inc.", "exchange": "NYSE"},
    {"symbol": "PG", "name": "Procter & Gamble Co.", "exchange": "NYSE"},
    {"symbol": "MA", "name": "Mastercard Inc.", "exchange": "NYSE"},
    {"symbol": "LLY", "name": "Eli Lilly and Company", "exchange": "NYSE"},
    {"symbol": "CVX", "name": "Chevron Corporation", "exchange": "NYSE"},
    {"symbol": "HD", "name": "Home Depot Inc.", "exchange": "NYSE"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "exchange": "NYSE"},
    {"symbol": "MRK", "name": "Merck & Co. Inc.", "exchange": "NYSE"},
    {"symbol": "KO", "name": "Coca-Cola Company", "exchange": "NYSE"},
    {"symbol": "COST", "name": "Costco Wholesale Corp.", "exchange": "NASDAQ"},
    {"symbol": "PEP", "name": "PepsiCo Inc.", "exchange": "NASDAQ"},
    {"symbol": "BAC", "name": "Bank of America Corp.", "exchange": "NYSE"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "exchange": "NASDAQ"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "exchange": "NASDAQ"},
    {"symbol": "CRM", "name": "Salesforce Inc.", "exchange": "NYSE"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "exchange": "NYSE"},
    {"symbol": "AMD", "name": "Advanced Micro Devices", "exchange": "NASDAQ"},
    {"symbol": "INTC", "name": "Intel Corporation", "exchange": "NASDAQ"},
    {"symbol": "CSCO", "name": "Cisco Systems Inc.", "exchange": "NASDAQ"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "exchange": "NYSE"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific", "exchange": "NYSE"},
    {"symbol": "DIS", "name": "Walt Disney Company", "exchange": "NYSE"},
    {"symbol": "PYPL", "name": "PayPal Holdings Inc.", "exchange": "NASDAQ"},
    {"symbol": "QCOM", "name": "Qualcomm Inc.", "exchange": "NASDAQ"},
    {"symbol": "T", "name": "AT&T Inc.", "exchange": "NYSE"},
    {"symbol": "VZ", "name": "Verizon Communications", "exchange": "NYSE"},
    {"symbol": "GS", "name": "Goldman Sachs Group", "exchange": "NYSE"},
    {"symbol": "MS", "name": "Morgan Stanley", "exchange": "NYSE"},
    {"symbol": "BKNG", "name": "Booking Holdings Inc.", "exchange": "NASDAQ"},
    {"symbol": "SBUX", "name": "Starbucks Corporation", "exchange": "NASDAQ"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "exchange": "NYSE"},
    {"symbol": "INTU", "name": "Intuit Inc.", "exchange": "NASDAQ"},
    {"symbol": "AMAT", "name": "Applied Materials Inc.", "exchange": "NASDAQ"},
    {"symbol": "MU", "name": "Micron Technology Inc.", "exchange": "NASDAQ"},
    {"symbol": "TXN", "name": "Texas Instruments Inc.", "exchange": "NASDAQ"},
    {"symbol": "SPGI", "name": "S&P Global Inc.", "exchange": "NYSE"},
    {"symbol": "BLK", "name": "BlackRock Inc.", "exchange": "NYSE"},
    # ── India — NSE ─────────────────────────────────────────────────────────
    {"symbol": "RELIANCE", "name": "Reliance Industries Ltd.", "exchange": "NSE"},
    {"symbol": "TCS", "name": "Tata Consultancy Services", "exchange": "NSE"},
    {"symbol": "HDFCBANK", "name": "HDFC Bank Ltd.", "exchange": "NSE"},
    {"symbol": "INFY", "name": "Infosys Ltd.", "exchange": "NSE"},
    {"symbol": "ICICIBANK", "name": "ICICI Bank Ltd.", "exchange": "NSE"},
    {"symbol": "HINDUNILVR", "name": "Hindustan Unilever Ltd.", "exchange": "NSE"},
    {"symbol": "BAJFINANCE", "name": "Bajaj Finance Ltd.", "exchange": "NSE"},
    {"symbol": "SBIN", "name": "State Bank of India", "exchange": "NSE"},
    {"symbol": "WIPRO", "name": "Wipro Ltd.", "exchange": "NSE"},
    {"symbol": "KOTAKBANK", "name": "Kotak Mahindra Bank Ltd.", "exchange": "NSE"},
    {"symbol": "BHARTIARTL", "name": "Bharti Airtel Ltd.", "exchange": "NSE"},
    {"symbol": "LT", "name": "Larsen & Toubro Ltd.", "exchange": "NSE"},
    {"symbol": "ASIANPAINT", "name": "Asian Paints Ltd.", "exchange": "NSE"},
    {"symbol": "AXISBANK", "name": "Axis Bank Ltd.", "exchange": "NSE"},
    {"symbol": "MARUTI", "name": "Maruti Suzuki India Ltd.", "exchange": "NSE"},
    {"symbol": "SUNPHARMA", "name": "Sun Pharmaceutical Industries", "exchange": "NSE"},
    {"symbol": "TITAN", "name": "Titan Company Ltd.", "exchange": "NSE"},
    {"symbol": "ULTRACEMCO", "name": "UltraTech Cement Ltd.", "exchange": "NSE"},
    {"symbol": "NESTLEIND", "name": "Nestle India Ltd.", "exchange": "NSE"},
    {"symbol": "POWERGRID", "name": "Power Grid Corp. of India", "exchange": "NSE"},
    {"symbol": "HCLTECH", "name": "HCL Technologies Ltd.", "exchange": "NSE"},
    {"symbol": "TATAMOTORS", "name": "Tata Motors Ltd.", "exchange": "NSE"},
    {"symbol": "TECHM", "name": "Tech Mahindra Ltd.", "exchange": "NSE"},
    {"symbol": "ONGC", "name": "Oil & Natural Gas Corp.", "exchange": "NSE"},
    {"symbol": "NTPC", "name": "NTPC Ltd.", "exchange": "NSE"},
    {"symbol": "ADANIPORTS", "name": "Adani Ports & SEZ Ltd.", "exchange": "NSE"},
    {"symbol": "JSWSTEEL", "name": "JSW Steel Ltd.", "exchange": "NSE"},
    {"symbol": "TATASTEEL", "name": "Tata Steel Ltd.", "exchange": "NSE"},
    {"symbol": "COALINDIA", "name": "Coal India Ltd.", "exchange": "NSE"},
    {"symbol": "DIVISLAB", "name": "Divi's Laboratories Ltd.", "exchange": "NSE"},
    {"symbol": "DRREDDY", "name": "Dr. Reddy's Laboratories", "exchange": "NSE"},
    {"symbol": "EICHERMOT", "name": "Eicher Motors Ltd.", "exchange": "NSE"},
    {"symbol": "GRASIM", "name": "Grasim Industries Ltd.", "exchange": "NSE"},
    {"symbol": "HEROMOTOCO", "name": "Hero MotoCorp Ltd.", "exchange": "NSE"},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank Ltd.", "exchange": "NSE"},
    {"symbol": "ITC", "name": "ITC Ltd.", "exchange": "NSE"},
    {"symbol": "M&M", "name": "Mahindra & Mahindra Ltd.", "exchange": "NSE"},
    {"symbol": "BRITANNIA", "name": "Britannia Industries Ltd.", "exchange": "NSE"},
    {"symbol": "BAJAJFINSV", "name": "Bajaj Finserv Ltd.", "exchange": "NSE"},
    {"symbol": "CIPLA", "name": "Cipla Ltd.", "exchange": "NSE"},
    {"symbol": "BPCL", "name": "Bharat Petroleum Corp.", "exchange": "NSE"},
    {"symbol": "APOLLOHOSP", "name": "Apollo Hospitals Enterprise", "exchange": "NSE"},
    {"symbol": "TATACONSUM", "name": "Tata Consumer Products Ltd.", "exchange": "NSE"},
    {"symbol": "HINDALCO", "name": "Hindalco Industries Ltd.", "exchange": "NSE"},
    {"symbol": "SBILIFE", "name": "SBI Life Insurance Co. Ltd.", "exchange": "NSE"},
    {"symbol": "HDFCLIFE", "name": "HDFC Life Insurance Co.", "exchange": "NSE"},
    {"symbol": "PIDILITIND", "name": "Pidilite Industries Ltd.", "exchange": "NSE"},
    {"symbol": "SIEMENS", "name": "Siemens Ltd.", "exchange": "NSE"},
    {"symbol": "ZOMATO", "name": "Zomato Ltd.", "exchange": "NSE"},
    {"symbol": "NYKAA", "name": "FSN E-Commerce (Nykaa)", "exchange": "NSE"},
]

EXCHANGE_FILTER_MAP: dict[ExchangeFilter, set[str]] = {
    ExchangeFilter.us: {"NYSE", "NASDAQ"},
    ExchangeFilter.india: {"NSE", "BSE"},
    ExchangeFilter.all: {"NYSE", "NASDAQ", "NSE", "BSE"},
}
