"""add historical_prices table

Revision ID: d9d6c2c804e7
Revises: b87416c6768d
Create Date: 2026-09-04 20:34:55.294874+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d6c2c804e7'
down_revision: Union[str, None] = 'b87416c6768d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trading_date', name='uix_historical_prices_symbol_date')
    )
    op.create_index('ix_historical_prices_symbol_date', 'historical_prices', ['symbol', 'trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_prices_symbol_date', table_name='historical_prices')
    op.drop_table('historical_prices')
    # ### end Alembic commands ###
