"""initial schema

Revision ID: e8b260225eb1
Revises: 
Create Date: 2026-08-29 18:11:06.052961+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8b260225eb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable CITEXT extension (needed for case-insensitive email uniqueness).
    # Must run before the 'users' table is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garch_fits',
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('omega', sa.Numeric(), nullable=True),
    sa.Column('alpha', sa.Numeric(), nullable=True),
    sa.Column('beta', sa.Numeric(), nullable=True),
    sa.Column('fitted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('regime_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('calm_probability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('stressed_probability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regime_states_captured_at', 'regime_states', ['captured_at'], unique=False)
    op.create_table('symbol_subscriptions',
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_user_id', 'portfolios', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_holdings_quantity_positive'),
    sa.CheckConstraint('average_price > 0', name='ck_holdings_average_price_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_holdings_portfolio_symbol')
    )
    op.create_index('ix_holdings_symbol', 'holdings', ['symbol'], unique=False)
    op.create_table('replays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('period_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_budgets',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('max_cvar', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('watch_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('high_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('breach_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_table('risk_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('var_95', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cvar_95', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('sharpe', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('risk_state', sa.Text(), nullable=False),
    sa.Column('risk_contribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_snapshots_portfolio_captured', 'risk_snapshots', ['portfolio_id', 'captured_at'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('num_paths', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulations_portfolio_created', 'simulations', ['portfolio_id', 'created_at'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_scenario', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('risk_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.Text(), nullable=False),
    sa.Column('to_state', sa.Text(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_snapshot_id'], ['risk_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_portfolio_fired', 'alerts', ['portfolio_id', 'fired_at'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('replay_id', sa.UUID(), nullable=False),
    sa.Column('predicted_breach_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('actual_breach_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('kupiec_statistic', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('p_value', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['replay_id'], ['replays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replay_daily_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('replay_id', sa.UUID(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('var_95', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_return', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('risk_state', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['replay_id'], ['replays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_replay_daily_states_replay_date', 'replay_daily_states', ['replay_id', 'trading_date'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    op.drop_index('ix_replay_daily_states_replay_date', table_name='replay_daily_states')
    op.drop_table('replay_daily_states')
    op.drop_table('backtest_results')
    op.drop_index('ix_alerts_portfolio_fired', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('ai_messages')
    op.drop_index('ix_simulations_portfolio_created', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('ix_risk_snapshots_portfolio_captured', table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_table('risk_budgets')
    op.drop_table('replays')
    op.drop_index('ix_holdings_symbol', table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('ai_conversations')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_portfolios_user_id', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_table('symbol_subscriptions')
    op.drop_index('ix_regime_states_captured_at', table_name='regime_states')
    op.drop_table('regime_states')
    op.drop_table('garch_fits')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS citext")
